FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y bash curl && \
    apt-get clean

WORKDIR /app

COPY jenkins-a/scripts ./scripts
COPY jenkins-a/tests/test_validate_ls.py .

RUN mkdir -p ./scripts/data

RUN chmod +x ./scripts/*.sh

CMD ["python", "test_validate_ls.py"]
