
services:
  jenkins-a:
    build: ./jenkins-a
    container_name: jenkins-a
    ports:
      - "8080:8080"
    volumes:
      - jenkins-a-data:/var/jenkins_home
      - ./jenkins-a/scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins-b:
    build: ./jenkins-b
    container_name: jenkins-b
    ports:
      - "8081:8080"
    volumes:
      - jenkins-b-data:/var/jenkins_home
      - ./jenkins-b/scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  jenkins-a-data:
  jenkins-b-data:
