FROM python:3.10-slim

RUN apt-get update && apt-get install -y curl && apt-get clean
COPY config/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app

COPY jenkins-b/scripts ./jenkins-b/scripts
COPY jenkins-b/tests .

CMD ["pytest", "-s"]
