FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y bash curl && \
    apt-get clean
COPY config/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR /app

COPY jenkins-a/tests/ .
COPY jenkins-a/scripts ./scripts


RUN mkdir -p ./scripts/data

RUN find ./scripts -name "*.sh" -exec chmod +x {} \;

CMD ["pytest", "-s"]
