FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y bash curl && \
    apt-get clean

WORKDIR /app

COPY config/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY jenkins-a/scripts ./scripts
COPY jenkins-a/tests ./tests
COPY jenkins-a/scripts/.env .env

CMD ["pytest", "tests/test_trigger_jenkins.py"]
